---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  url: https://grafana.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: "8.5.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  targetNamespace: grafana
  install:
    crds: CreateReplace
  values:
    adminPassword: admin
    podAnnotations:
      "consul.hashicorp.com/connect-inject": "true"
    persistence:
      enabled: true
      type: pvc
      existingClaim: grafana-nfs
