---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system # Replace with your namespace for Prometheus
spec:
  interval: 5m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: "25.30.0" # Set the desired version
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  targetNamespace: prometheus
  values:
    alertmanager:
      enabled: false
    server:
      replicaCount: 1
      podAnnotations:
        "consul.hashicorp.com/connect-service-port": "9090"
        "consul.hashicorp.com/connect-service": "prometheus-server"
        "consul.hashicorp.com/connect-inject": "true"
      global:
        scrape_interval: 30s
      persistentVolume:
        enabled: true
        existingClaim: prometheus-nfs
    extraScrapeConfigs: |
      - job_name: 'pihole-exporter'
        metrics_path: /metrics
        static_configs:
          - targets:
            - "192.168.0.55:9617"
      - job_name: 'haproxy-node-exporters'
        static_configs:
          - targets:
            - "192.168.0.55:9100"
            - "192.168.0.63:9100"
