---
apiVersion: v1
kind: Namespace
metadata:
  name: rag-qdrant
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: qdrant
  namespace: flux-system
spec:
  url: https://qdrant.github.io/qdrant-helm
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qdrant
  namespace: flux-system
spec:
  interval: 5m
  releaseName: qdrant
  chart:
    spec:
      chart: qdrant
      version: "0.8.6" # Latest stable version as of 2025
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: flux-system
  targetNamespace: rag-qdrant
  values:
    replicaCount: 1
    image:
      tag: "v1.11.3" # Latest stable Qdrant version
    persistence:
      enabled: false
    resources:
      requests:
        memory: "2Gi"
        cpu: "250m"
      limits:
        memory: "2Gi"
    service:
      type: ClusterIP
      port: 6333
      grpcPort: 6334
    config:
      cluster:
        enabled: false # Set to true if you need clustering
