---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs
  namespace: grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/kube_pv/grafana
    server: 10.0.4.140
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-nfs
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: grafana-nfs-pv
