---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-nfs
  namespace: home-assistant
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/kube_pv/home-assistant
    server: 10.0.4.140
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-nfs
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: home-assistant-nfs
