---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs
  namespace: grafana
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/kube_pv/prometheus
    server: 10.0.4.140
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-nfs
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: prometheus-nfs
