---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferenceGrant
metadata:
  name: consul-reference-grant
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: consul-ingress
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route-api
spec:
  parentRefs:
    - name: api-gateway
      namespace: consul-ingress
  hostnames:
    - home-assistant
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: home-assistant
          port: 8123
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: home-assistant
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "home-assistant"
        "consul.hashicorp.com/connect-service-port": "8123"
    spec:
      hostNetwork: false
      containers:
        - name: home-assitant
          image: ghcr.io/home-assistant/home-assistant:2024.11.2
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: home-assistant-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  type: ClusterIP
  ports:
    - port: 8123
      protocol: TCP
  selector:
    app: home-assistant
